### ISSUE TITLE
Stworzenie diagramów

### ISSUE THREAD

**Issue by Gawinooo** [ProjektZespolowyDGOGPGPA/Dokumentacja#21]
Zadanie polega na stworzeniu kompletu diagramów związanego z projektem tzn. diagram przypadków użycia, diagram klas,diagram przepływu danych, diagram związków encji, diagram przejść stanów, diagram aktywności, diagram sekwencji, diagram współpracy, diagram komponentów. Termin do którego plik ma być zamieszczony to 05.06. br. 
Diagram komponentów i diagram współpracy- @Cry2tor 
Diagram klas- @GallAn0nim 
Diagram przejść stanów i diagram aktywności- @Lamozaur
Diagram przypadków użycia,diagram przepływu danych,diagram encja-związek,diagram sekwencji-kierownik

**Comment by p4we3** [comment]
Nie mogę znaleźć nic o diagramie współpracy. Ewentualnie mogę dorobić później jeśli znajdę jakieś informacje. Nie do końca wiem jak wykonać ten diagram komponentów z uwagi na to, że oskar wykonał większość pracy nad silnikiem i on prędzej będzie wiedział jak to działa i jak się komunikuje. Ja potrzebowałbym aktualny diagram klas najpierw. Wstawiam co zrobiłem.
